/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as HilfeRouteImport } from './routes/hilfe'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KurenRouteImport } from './routes/kuren'
import { Route as ManufakturRouteImport } from './routes/manufaktur'
import { Route as MoosRouteImport } from './routes/moos'
import { Route as TinkturenRouteImport } from './routes/tinkturen'
import { Route as VersandRouteImport } from './routes/versand'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const HilfeRoute = HilfeRouteImport.update({
  id: '/hilfe',
  path: '/hilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KurenRoute = KurenRouteImport.update({
  id: '/kuren',
  path: '/kuren',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufakturRoute = ManufakturRouteImport.update({
  id: '/manufaktur',
  path: '/manufaktur',
  getParentRoute: () => rootRouteImport,
} as any)
const MoosRoute = MoosRouteImport.update({
  id: '/moos',
  path: '/moos',
  getParentRoute: () => rootRouteImport,
} as any)
const TinkturenRoute = TinkturenRouteImport.update({
  id: '/tinkturen',
  path: '/tinkturen',
  getParentRoute: () => rootRouteImport,
} as any)
const VersandRoute = VersandRouteImport.update({
  id: '/versand',
  path: '/versand',
  getParentRoute: () => rootRouteImport,
} as any)
const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/hilfe': typeof HilfeRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kuren': typeof KurenRoute
  '/manufaktur': typeof ManufakturRoute
  '/moos': typeof MoosRoute
  '/tinkturen': typeof TinkturenRoute
  '/versand': typeof VersandRoute
  '/warenkorb': typeof WarenkorbRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/hilfe': typeof HilfeRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kuren': typeof KurenRoute
  '/manufaktur': typeof ManufakturRoute
  '/moos': typeof MoosRoute
  '/tinkturen': typeof TinkturenRoute
  '/versand': typeof VersandRoute
  '/warenkorb': typeof WarenkorbRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/hilfe': typeof HilfeRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kuren': typeof KurenRoute
  '/manufaktur': typeof ManufakturRoute
  '/moos': typeof MoosRoute
  '/tinkturen': typeof TinkturenRoute
  '/versand': typeof VersandRoute
  '/warenkorb': typeof WarenkorbRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agb'
    | '/datenschutz'
    | '/hilfe'
    | '/impressum'
    | '/kontakt'
    | '/kuren'
    | '/manufaktur'
    | '/moos'
    | '/tinkturen'
    | '/versand'
    | '/warenkorb'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agb'
    | '/datenschutz'
    | '/hilfe'
    | '/impressum'
    | '/kontakt'
    | '/kuren'
    | '/manufaktur'
    | '/moos'
    | '/tinkturen'
    | '/versand'
    | '/warenkorb'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agb'
    | '/datenschutz'
    | '/hilfe'
    | '/impressum'
    | '/kontakt'
    | '/kuren'
    | '/manufaktur'
    | '/moos'
    | '/tinkturen'
    | '/versand'
    | '/warenkorb'
    | '/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  HilfeRoute: typeof HilfeRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  KurenRoute: typeof KurenRoute
  ManufakturRoute: typeof ManufakturRoute
  MoosRoute: typeof MoosRoute
  TinkturenRoute: typeof TinkturenRoute
  VersandRoute: typeof VersandRoute
  WarenkorbRoute: typeof WarenkorbRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hilfe': {
      id: '/hilfe'
      path: '/hilfe'
      fullPath: '/hilfe'
      preLoaderRoute: typeof HilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuren': {
      id: '/kuren'
      path: '/kuren'
      fullPath: '/kuren'
      preLoaderRoute: typeof KurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufaktur': {
      id: '/manufaktur'
      path: '/manufaktur'
      fullPath: '/manufaktur'
      preLoaderRoute: typeof ManufakturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moos': {
      id: '/moos'
      path: '/moos'
      fullPath: '/moos'
      preLoaderRoute: typeof MoosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tinkturen': {
      id: '/tinkturen'
      path: '/tinkturen'
      fullPath: '/tinkturen'
      preLoaderRoute: typeof TinkturenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versand': {
      id: '/versand'
      path: '/versand'
      fullPath: '/versand'
      preLoaderRoute: typeof VersandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  HilfeRoute: HilfeRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  KurenRoute: KurenRoute,
  ManufakturRoute: ManufakturRoute,
  MoosRoute: MoosRoute,
  TinkturenRoute: TinkturenRoute,
  VersandRoute: VersandRoute,
  WarenkorbRoute: WarenkorbRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
